# Generated by Django 6.0.6 on 2026-06-30 10:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UGQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'UG qualification',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('PHC', 'PHC'), ('CHC', 'CHC')], max_length=3)),
                ('sanctioned_vacancies', models.PositiveIntegerField(default=0)),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='portal.taluka')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['taluka__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('father_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('address', models.TextField(verbose_name='correspondence address')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('ug_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_type', models.CharField(choices=[('CGPA', 'CGPA'), ('PERCENTAGE', 'Percentage')], max_length=10)),
                ('higher_qualification', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ug_qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='portal.ugqualification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Priority 1'), (2, 'Priority 2'), (3, 'Priority 3')])),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='portal.applicant')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preferences', to='portal.facility')),
            ],
            options={
                'ordering': ['applicant', 'priority'],
                'constraints': [models.UniqueConstraint(fields=('applicant', 'priority'), name='unique_applicant_priority'), models.UniqueConstraint(fields=('applicant', 'facility'), name='unique_applicant_facility')],
            },
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('taluka', 'name', 'type'), name='unique_facility_per_taluka'),
        ),
    ]
